# Generated by Django 5.2.7 on 2026-01-22 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_configuration_price_in_rupees'),
        ('utility', '0005_category_sub_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_amenities', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='amenities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_amenities_items', to='utility.projectamenities'),
        ),
    ]
