# Generated by Django 5.0.2 on 2026-01-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_amenities_project_alter_amenities_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='towers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
