# Generated by Django 5.0.2 on 2026-01-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_towers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='banner_img/'),
        ),
    ]
