# Generated by Django 5.2.7 on 2026-01-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_banner_img'),
        ('utility', '0005_category_sub_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='target_possession_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='Select Target Possession Month', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_possession_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_possession_year', to='utility.possessionin'),
        ),
    ]
