# Generated by Django 5.2.7 on 2026-06-23 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_target_possession_month_and_more'),
        ('utility', '0007_delete_facility_delete_furnishingitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='land_parce',
            new_name='land_parcel',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='sold_out',
        ),
        migrations.RemoveField(
            model_name='project',
            name='banner_img',
        ),
        migrations.RemoveField(
            model_name='project',
            name='floor_plan',
        ),
        migrations.RemoveField(
            model_name='project',
            name='master_plan',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target_possession_month',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target_possession_year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='towers',
        ),
        migrations.AddField(
            model_name='project',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='amenities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='utility.projectamenities'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='price_in_rupees',
            field=models.IntegerField(help_text='Enter price in total rupees (e.g., 5000000).', verbose_name='Price (in ₹)'),
        ),
        migrations.AlterField(
            model_name='connectivity',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='possession_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.possessionin'),
        ),
    ]
