# Generated by Django 5.2.7 on 2026-02-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
