# Generated by Django 5.2.7 on 2026-02-16 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rentalproperty_floor'),
        ('rent_utility', '0002_tenanttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='tenant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_utility.tenanttype'),
        ),
    ]
