# Generated by Django 5.2.7 on 2026-02-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_rentalproperty_tenant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='About Section Title')),
                ('about_description', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('about_readmore', models.TextField(blank=True, null=True, verbose_name='Read More Description')),
                ('key_highlights', models.TextField(blank=True, help_text='Enter each highlight on a new line', null=True)),
            ],
        ),
    ]
