# Generated by Django 5.2.7 on 2026-02-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_aboutproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproperty',
            name='rental',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_section', to='rent.rentalproperty'),
        ),
        migrations.AlterField(
            model_name='aboutproperty',
            name='about_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutproperty',
            name='about_readmore',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutproperty',
            name='about_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
