# Generated by Django 5.2.7 on 2026-02-16 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_aboutproperty_rental_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutproperty',
            name='key_highlights',
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='google_map_iframe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutproperty',
            name='rental',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_section', to='rent.rentalproperty'),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
