# Generated by Django 5.2.7 on 2026-02-16 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_remove_aboutproperty_key_highlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='banner_img/'),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='featured_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='master_plan',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='youtube_embed_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='YouTube Video ID'),
        ),
        migrations.CreateModel(
            name='RentalConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=50)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectivities', to='rent.rentalproperty')),
            ],
        ),
    ]
