# Generated by Django 5.2.7 on 2026-02-16 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_rentalproperty_active_rentalproperty_banner_img_and_more'),
        ('utility', '0007_delete_facility_delete_furnishingitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_amenity_items', to='utility.propertyamenities')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='rent.rentalproperty')),
            ],
            options={
                'unique_together': {('rental', 'amenity')},
            },
        ),
    ]
