# Generated by Django 5.2.7 on 2026-02-16 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_rentalamenity'),
        ('rent_utility', '0002_tenanttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalFurnishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_utility.furnishingitem')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnishings', to='rent.rentalproperty')),
            ],
            options={
                'unique_together': {('rental', 'item')},
            },
        ),
    ]
