# Generated by Django 5.2.7 on 2026-02-16 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_rentalfurnishing'),
        ('rent_utility', '0004_alter_furnishingitem_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_utility.facility')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='rent.rentalproperty')),
            ],
            options={
                'unique_together': {('rental', 'facility')},
            },
        ),
    ]
