# Generated by Django 5.2.7 on 2026-02-16 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_owner_rentalproperty_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalproperty',
            name='owner',
        ),
        migrations.CreateModel(
            name='OwnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('owner_type', models.CharField(choices=[('Individual', 'Individual Owner'), ('Dealer', 'Property Dealer')], default='Individual', max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('locality', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='owners/')),
                ('is_online', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_details', to='rent.rentalproperty')),
            ],
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
