# Generated by Django 5.2.7 on 2026-02-16 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_remove_rentalproperty_owner_ownerdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_from', models.DateField()),
                ('preferred_tenant', models.CharField(choices=[('Family', 'Family'), ('Bachelors', 'Bachelors'), ('Family/Bachelors', 'Family / Bachelors')], max_length=30)),
                ('lease_duration', models.PositiveIntegerField(help_text='In Months')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_details', to='rent.rentalproperty')),
            ],
        ),
    ]
