# Generated by Django 5.2.7 on 2026-02-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_rentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='rent.rentalproperty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
