# Generated by Django 5.2.7 on 2026-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0014_rentalfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
