# Generated by Django 5.2.7 on 2026-02-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0015_rentalenquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalEnquiry',
        ),
    ]
