# Generated by Django 5.2.7 on 2026-02-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0017_rentalenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='posted_by',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Builder', 'Builder'), ('Dealer', 'Dealer'), ('Feature Dealer', 'Feature Dealer')], default='Owner', max_length=20),
        ),
    ]
