# Generated by Django 5.2.7 on 2026-02-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0018_rentalproperty_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproperty',
            name='posted_by',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Builder', 'Builder'), ('Dealer', 'Dealer'), ('Feature Dealer', 'Feature Dealer')], default='Owner', max_length=20, null=True),
        ),
    ]
