# Generated by Django 5.2.7 on 2026-02-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0019_alter_rentalproperty_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='available_from',
            field=models.CharField(blank=True, choices=[('Any   Time', 'Any Time'), ('Immediately', 'Immediately'), ('Within 15 Days', 'Within 15 days'), ('Within 1 Month', 'Within 1 Month'), ('Within 3 Month', 'Within 3 Month'), ('After 3 Months', 'After 3 Months')], default='Any Time', max_length=20, null=True),
        ),
    ]
