# Generated by Django 5.2.7 on 2026-02-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0021_visitschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='age_of_property',
            field=models.CharField(blank=True, choices=[('0-1 years old', '0-1 years old'), ('1-5 years old', '1-5 years old'), ('5-10 years old', '5-10 years old'), ('10+ years old', '10+ years old'), ('20+ years old', '20+ years old')], default='Any Time', max_length=20, null=True),
        ),
    ]
