# Generated by Django 5.2.7 on 2026-02-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0022_rentalproperty_age_of_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproperty',
            name='available_from',
            field=models.CharField(blank=True, choices=[('Any Time', 'Any Time'), ('Immediately', 'Immediately'), ('Within 15 Days', 'Within 15 Days'), ('Within 1 Month', 'Within 1 Month'), ('Within 3 Months', 'Within 3 Months'), ('After 3 Months', 'After 3 Months')], default='Any Time', max_length=30),
        ),
    ]
