# Generated by Django 5.2.7 on 2026-02-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0023_alter_rentalproperty_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproperty',
            name='age_of_property',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
