# Generated by Django 5.0.2 on 2026-05-14 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0024_alter_rentalproperty_age_of_property'),
        ('rent_utility', '0006_alter_facility_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentalFurnishing',
            new_name='FurnishingAmenity',
        ),
        migrations.RemoveField(
            model_name='rentdetails',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='rentalproperty',
            name='banner_img',
        ),
        migrations.RemoveField(
            model_name='rentalproperty',
            name='floor_plan',
        ),
        migrations.RemoveField(
            model_name='rentalproperty',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rentalproperty',
            name='master_plan',
        ),
        migrations.RemoveField(
            model_name='rentalproperty',
            name='tenant_type',
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='total_floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='age_of_property',
            field=models.CharField(blank=True, choices=[('0-1 years old', '0-1 years old'), ('1-5 years old', '1-5 years old'), ('5-10 years old', '5-10 years old'), ('10+ years old', '10+ years old'), ('20+ years old', '20+ years old')], default='0-1 years old', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='furnishing_type',
            field=models.CharField(blank=True, choices=[('Furnished', 'Furnished'), ('Semi Furnished', 'Semi Furnished'), ('Un Furnished', 'Un Furnished')], default='Furnished', max_length=30),
        ),
        migrations.CreateModel(
            name='ChargesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paper_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moving_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_tenant', models.CharField(blank=True, max_length=100, null=True)),
                ('lease_duration', models.PositiveIntegerField(help_text='In Months')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_details', to='rent.rentalproperty')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('Individual', 'Individual Owner'), ('Dealer', 'Property Dealer'), ('Builder', 'Builder')], default='Individual', max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('locality', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='owners/')),
                ('about', models.TextField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_properties', to='rent.ownerprofile'),
        ),
        migrations.CreateModel(
            name='RentalPropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rental/property/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='rent.rentalproperty')),
            ],
            options={
                'ordering': ['-is_primary', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='OwnerDetails',
        ),
        migrations.DeleteModel(
            name='RentDetails',
        ),
    ]
