# Generated by Django 5.0.1 on 2026-01-12 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('utility', '0002_bank_possessionin_projectamenities_propertyamenities_and_more'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]


    operations = [
        migrations.CreateModel(
            name='GoogleCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_for_emails', models.CharField(blank=True, max_length=255, null=True)),
                ('category_text', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('type', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('street', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('city_text', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, db_index=True, max_length=300, null=True, unique=True)),
                ('google_id', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('cid', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('business_status', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('working_hours', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow Up'), ('Not_received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number', 'Invalid Number'), ('Send Ditails', 'Send Ditails')], default='New', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_googlecompany_assigned', to='response.staff')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_googlecompany_created', to=settings.AUTH_USER_MODEL)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.locality')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('sub_locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.sub_locality')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_googlecompany_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. Google Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New Followup', 'New Followup'), ('Re Followup', 'Re Followup'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], max_length=25)),
                ('followup_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_followup_assigned', to='response.staff')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_followup_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_followup_updated', to=settings.AUTH_USER_MODEL)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='realtypms.googlecompany')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_comment_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_comment_updated', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='realtypms.googlecompany')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New Meeting', 'New Meeting'), ('Re Meeting', 'Re Meeting'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], max_length=25)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_meeting_assigned', to='response.staff')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='realtypms.googlecompany')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_meeting_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_meeting_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_for', models.CharField(choices=[('Telling Meeting', 'Telling Meeting'), ('Door To Door', 'Door To Door'), ('Site Visit', 'Site Visit'), ('Follow Up', 'Follow Up'), ('Negotiation', 'Negotiation')], max_length=50)),
                ('visit_type', models.CharField(choices=[('1st Visit', '1st Visit'), ('2nd Visit', '2nd Visit'), ('3rd Visit', '3rd Visit'), ('4th Visit', '4th Visit'), ('5th Visit', '5th Visit')], max_length=50)),
                ('visit_status', models.CharField(choices=[('Deal_Close', 'Deal Close'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow Up'), ('Owner not In Office', 'Owner not In Office'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested')], max_length=50)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='realtypms.googlecompany')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_visit_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='call_recordings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='realtypms.googlecompany')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtypms_voice_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
