# Generated by Django 5.2.7 on 2025-12-12 17:15
from django.db import migrations
import django_ckeditor_5.fields
        
class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_setting_button_color_setting_rera_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='cookies',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='disclaimer',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='privacy_policy',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='terms_conditions',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
