# Generated by Django 5.2.7 on 2026-01-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_footerlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='subtitle',
        ),
    ]
