# Generated by Django 5.2.7 on 2026-01-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_footerlink_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
