# Generated by Django 5.2.7 on 2026-02-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contactenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='type',
            field=models.CharField(blank=True, choices=[('flat', 'Looking for a Flat'), ('owner', 'Property Owner')], max_length=20, null=True),
        ),
    ]
