# Generated by Django 5.2.7 on 2026-06-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contactenquiry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossessionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_to_move', models.ImageField(default=0, upload_to='metrics/')),
                ('under_construction', models.ImageField(default=0, upload_to='metrics/')),
                ('upcoming', models.ImageField(default=0, upload_to='metrics/')),
            ],
        ),
    ]
