# Generated by Django 5.2.7 on 2026-01-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtypms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecompany',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Connected', 'Connected'), ('Shared_Details', 'Shared Details'), ('No_Requirement', 'No Requirement'), ('Call_Back', 'Call Back'), ('Follow_Up', 'Follow Up'), ('Call_Back_Weekend', 'Call Back Weekend'), ('Call_Back_Weekdays', 'Call Back Weekdays'), ('Visit_On', 'Visit On.....'), ('Already_Visited', 'Already Visited'), ('Ringing', 'Ringing'), ('Not_Reachable', 'Not Reachable'), ('Not_Available', 'Not Available'), ('Out_Of_Service', 'Out Of Service'), ('Switched_Off', 'Switched Off'), ('Not_Answered', 'Not Answered'), ('Not_Interested', 'Not Interested'), ('Interested', 'Interested'), ('Some_Other_Project', 'Some other project'), ('Low_Budget', 'Low Budget'), ('RTM_Commercial', 'RTM. Commercial'), ('Rental_Commercial', 'Rental Commercial'), ('RTM_Residential', 'RTM. Residential'), ('Rental_Residential', 'Rental Residential'), ('Already_Purchased', 'All Ready Purchased'), ('Not_received', 'Not Received'), ('They_Will_Connect', 'They Will Connect'), ('Call_Later', 'Call later'), ('Call_Tomorrow', 'Call Tomorrow'), ('Invalid_Number', 'Invalid Number'), ('Send_Details', 'Send Details')], default='New', max_length=25),
        ),
    ]
