# Generated by Django 5.2.7 on 2026-01-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtypms', '0002_alter_googlecompany_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecompany',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Follow_Up', 'Follow Up'), ('Visit_On', 'Visit On.....'), ('Busy', 'Busy'), ('Ringing', 'Ringing'), ('Disconnect', 'Disconnect'), ('Invalid No', 'Invalid No'), ('Switched_Off', 'Switched Off'), ('Not Reachable.', 'Not Reachable.'), ('Not Available', 'Not Available'), ('Not_Interested', 'Not Interested'), ('Out Of Service', 'Out Of Service'), ('Already_Visited', 'Already Visited'), ('🤝 Deal Closed', '🤝 Deal Closed'), ('Site visit Ongoing', 'Site visit Ongoing'), ('All Ready Purchased. ', 'All Ready Purchased. ')], default='New', max_length=25),
        ),
    ]
