# Generated by Django 5.2.7 on 2026-01-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_locality_featured_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='home_loan_partner',
            field=models.BooleanField(default=False),
        ),
    ]
