# Generated by Django 5.2.7 on 2026-01-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_bank_home_loan_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='home_loan_partner',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
