# Generated by Django 5.2.7 on 2026-02-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_category_sub_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='utility/facility/icons/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FurnishingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='utility/furnishing/icons/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Furnishing Item',
                'verbose_name_plural': 'Furnishing Items',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='propertyamenities',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
