# Generated by Django 5.2.7 on 2026-02-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_facility_furnishingitem_alter_propertyamenities_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='FurnishingItem',
        ),
        migrations.AlterField(
            model_name='propertyamenities',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
