# Generated by Django 5.2.7 on 2026-02-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='utility/facility/icons/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FurnishingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='utility/furnishing/icons/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Furnishing Item',
                'verbose_name_plural': 'Furnishing Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='property/amenities/')),
            ],
            options={
                'verbose_name_plural': 'Property Amenities',
                'ordering': ['name'],
            },
        ),
    ]
