# Generated by Django 5.2.7 on 2026-02-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenant Type',
                'verbose_name_plural': 'Tenant Types',
                'ordering': ['name'],
            },
        ),
    ]
