# Generated by Django 5.2.7 on 2026-02-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_utility', '0002_tenanttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnishingitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=''),
        ),
    ]
