# Generated by Django 5.2.7 on 2026-02-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_utility', '0003_alter_furnishingitem_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnishingitem',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
