# Generated by Django 5.2.7 on 2026-02-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_utility', '0005_alter_facility_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.CharField(blank=True, help_text='Enter icon class (e.g. fa-solid fa-car)', max_length=100, null=True),
        ),
    ]
