# Generated by Django 5.0.2 on 2026-05-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0025_rename_rentalfurnishing_furnishingamenity_and_more'),
        ('rent_utility', '0006_alter_facility_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyAmenities',
        ),
        migrations.DeleteModel(
            name='TenantType',
        ),
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: fa-solid fa-car', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='furnishingitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: fa-solid fa-bed', max_length=100, null=True, unique=True),
        ),
    ]
